# Generated by Django 6.0 on 2025-12-18 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, default=2025, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
