# Generated by Django 6.0 on 2025-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votesession',
            options={'ordering': ['-event_date_time']},
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'vote_session'), name='unique_voting'),
        ),
    ]
